# Generated by Django 5.0.6 on 2025-10-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('lux', 'Lux')], default='lux', max_length=10),
        ),
        migrations.AddField(
            model_name='barber',
            name='password',
            field=models.CharField(default='123456', max_length=255),
        ),
    ]
